EmergencyAccidentReporting/Controllers/EventsController.cs
using EmergencyAccidentReporting.Models;
using Microsoft.AspNetCore.Mvc;

namespace EmergencyAccidentReporting.Controllers
{
    public class EventsController : Controller
    {
        DataContext dal = new DataContext();
        public IActionResult Index(int id)
        {
            Events events = dal.eventss.Find(id);
            ViewData["Title"] = events.Title;

            return View(events);

        }
    }
}

EmergencyAccidentReporting/Views/Admin/AccidentReports.cshtml
@model IEnumerable<Accident>
@{
    Layout = "_LayoutAdmin";
}

@section Scripts{

    <script>
        $(document).ready(function() {

            const x = document.getElementById("demo");
            function getLocation() {
                if (navigator.geolocation) {
                    navigator.geolocation.getCurrentPosition(showPosition);
                } else {
                    x.innerHTML = "Geolocation is not supported by this browser.";
                }
            }

            function showPosition(position) {


                console.log(position.coords.latitude);
                console.log(position.coords.longitude);
                var lat = position.coords.latitude;
                var lon = position.coords.longitude;
                var concatedvalue = lat + "," + lon;
                console.log(concatedvalue);
                document.getElementById("coordinate").value = lat + "," + lon;


            }

            getLocation();
                        });

    </script>
}

    <div class="app-container">
        <!-- begin app-nabar -->
        <!-- end app-navbar -->
        <!-- begin app-main -->
        <div class="app-main" id="main">
            <!-- begin container-fluid -->
            <div class="container-fluid">

                <div class="row">
                    <div class="col-md-12 m-b-30">
                        <!-- begin page title -->
                        <div class="d-block d-lg-flex flex-nowrap align-items-center">
                            <div class="page-title mr-4 pr-4 border-right">
                                <h1>Accident Reports</h1>
                            </div>


                        </div>
                        <!-- end page title -->
                    </div>
                </div>


                <div class="row">
                    <div class="col-sm-12">
                        <table class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Accident Location</th>
                                    <th>contact</th>
                                    <th>Number</th>
                                    <th>Reporters Name</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                            {

                                <tr>
                                    <td>@item.Location</td>
                                    <td>@item.Contact</td>
                                    <td>@item.Number</td>
                                    <td>@item.ReportersName</td>
                                    <td>
                                        <a role="button" class="btn btn-primary" asp-controller="Admin" asp-action="ViewAccidentPage" asp-route-id="@item.Id">View</a>
                                        <a role="button" class="btn btn-secondary" asp-controller="Admin" asp-action="Route" asp-route-usercoordinate="@item.Geolocation" asp-route-mycoordinate="26.560588465928983,88.08661724010332">Route</a>
                                        

                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>

EmergencyAccidentReporting/Views/Admin/AddEvents.cshtml
@model EventsModel
@{
    Layout = "_LayoutAdmin";
}


<head>
      <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Au Register Forms by Colorlib</title>

    <!-- Icons font CSS-->
    <link href="~/vehicle/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">
    <link href="~/vehicle/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="~/vehicle/vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="~/vehicle/vendor/datepicker/daterangepicker.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="~/vehicle/css/main.css" rel="stylesheet" media="all">
</head>

<div class="app-container">
    <!-- begin app-nabar -->
    <!-- end app-navbar -->
    <!-- begin app-main -->
    <div class="app-main" id="main">
        <!-- begin container-fluid -->
        <div class="container-fluid">

            <div class="row">
                <div class="col-md-12 m-b-30">
                    <!-- begin page title -->
                    <div class="d-block d-lg-flex flex-nowrap align-items-center">
                        <div class="page-title mr-4 pr-4 border-right">
                            <h1>Events Register</h1>
                        </div>


                    </div>
                    <!-- end page title -->
                </div>
            </div>

            <div class="row">
                <div class="card">
                    <div class="card-header">
                        Events
                    </div>
                    <div class="card-body">
                        <form method="post" asp-action="AddEvents" asp-controller="Admin" enctype="multipart/form-data">
                            <div class="form-row">
                                <div class="name">
                                    <label class="control-label" asp-for="Title"></label>
                                </div>
                                <div class="value">
                                    <div class="input-group">
                                        <input class="input--style-5" type="text" asp-for="Title">
                                    </div>
                                    <span class="text-danger" asp-validation-for="Title"></span>
                                </div>
                            </div>

                            <div class="form-row">
                                <div class="name">
                                    <label class="control-label" asp-for="EventsDetail"></label>
                                </div>
                                <div class="value">
                                    <div class="input-group">
                                        <textarea rows="2" class="form-control input--style-5" asp-for="EventsDetail"></textarea>
                                    </div>
                                    <span class="text-danger" asp-validation-for="EventsDetail"></span>
                                </div>
                            </div>

                            <div class="form-row">
                                <div class="name">
                                    <label class="control-label" asp-for="ImgUrl"></label>

                                </div>
                                <div class="value">
                                    <div class="input-group">
                                        <input type="file" class="form-control" id="email1" asp-for="ImgUrl" placeholder="Photos" accept="image/*" />
                                    </div>
                                    <span class="text-danger" asp-validation-for="ImgUrl"></span>

                                </div>
                            </div>
                            <div class="form-row">
                                <div class="input-group">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            </div>
                        </form>

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

                                <!-- Jquery JS-->
<script src="~/vehicle/vendor/jquery/jquery.min.js"></script>
<!-- Vendor JS-->
<script src="~/vehicle/vendor/select2/select2.min.js"></script>
<script src="~/vehicle/vendor/datepicker/moment.min.js"></script>
<script src="~/vehicle/vendor/datepicker/daterangepicker.js"></script>

<!-- Main JS-->
<script src="~/vehicle/js/global.js"></script>

EmergencyAccidentReporting/Views/Admin/AddNews.cshtml
@model NewsModel
@{
    Layout = "_LayoutAdmin";
}


<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Au Register Forms by Colorlib</title>

    <!-- Icons font CSS-->
    <link href="~/vehicle/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">
    <link href="~/vehicle/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="~/vehicle/vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="~/vehicle/vendor/datepicker/daterangepicker.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="~/vehicle/css/main.css" rel="stylesheet" media="all">
</head>

<div class="app-container">
    <!-- begin app-nabar -->
    <!-- end app-navbar -->
    <!-- begin app-main -->
    <div class="app-main" id="main">
        <!-- begin container-fluid -->
        <div class="container-fluid">

            <div class="row">
                <div class="col-md-12 m-b-30">
                    <!-- begin page title -->
                    <div class="d-block d-lg-flex flex-nowrap align-items-center">
                        <div class="page-title mr-4 pr-4 border-right">
                            <h1>News Register</h1>
                        </div>


                    </div>
                    <!-- end page title -->
                </div>
            </div>

            <div class="row">
                <div class="card">
                    <div class="card-header">
                        News
                    </div>
                    <div class="card-body">
                        <form method="post" asp-action="AddNews" asp-controller="Admin" enctype="multipart/form-data">
                            <div class="form-row">
                                <div class="name">
                                    <label class="control-label" asp-for="Title"></label>
                                </div>
                                <div class="value">
                                    <div class="input-group">
                                        <input class="input--style-5" type="text" asp-for="Title">
                                    </div>
                                    <span class="text-danger" asp-validation-for="Title"></span>
                                </div>
                            </div>

                            <div class="form-row">
                                <div class="name">
                                    <label class="control-label" asp-for="Category"></label>
                                </div>
                                <div class="value">
                                    <div class="input-group">
                                        <div class="rs-select2 js-select-simple select--no-search">
                                            <select asp-for="Category" asp-items="new SelectList(ViewBag.cat)">
                                            </select>
                                            <div class="select-dropdown"></div>
                                        </div>
                                    </div>

                                </div>
                            </div>


                            <div class="form-row">
                                <div class="name">
                                    <label class="control-label" asp-for="NewsDetail"></label>
                                </div>
                                <div class="value">
                                    <div class="input-group">
                                        <textarea rows="2" class="form-control input--style-5" asp-for="NewsDetail"></textarea>
                                    </div>
                                    <span class="text-danger" asp-validation-for="NewsDetail"></span>
                                </div>
                            </div>

                            <div class="form-row">
                                <div class="name">
                                    <label class="control-label" asp-for="ImgUrl"></label>

                                </div>
                                <div class="value">
                                    <div class="input-group">
                                        <input type="file" class="form-control" id="email1" asp-for="ImgUrl" placeholder="Photos" accept="image/*" />
                                    </div>
                                    <span class="text-danger" asp-validation-for="ImgUrl"></span>

                                </div>
                            </div>
                            <div class="form-row">
                                <div class="input-group">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            </div>
                        </form>

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<!-- Jquery JS-->
<script src="~/vehicle/vendor/jquery/jquery.min.js"></script>
<!-- Vendor JS-->
<script src="~/vehicle/vendor/select2/select2.min.js"></script>
<script src="~/vehicle/vendor/datepicker/moment.min.js"></script>
<script src="~/vehicle/vendor/datepicker/daterangepicker.js"></script>

<!-- Main JS-->
<script src="~/vehicle/js/global.js"></script>

EmergencyAccidentReporting/Views/Admin/Index.cshtml
@page
@model EmergencyAccidentReporting.Views.Admin.IndexModel
@{
    Layout = "_LayoutAdmin";
}


<div class="app-container">
    <!-- begin app-nabar -->
    <!-- end app-navbar -->
    <!-- begin app-main -->
    <div class="app-main" id="main">
        <!-- begin container-fluid -->
        <div class="container-fluid">
            <!-- begin row -->
            <div class="row">
                <div class="col-md-12 m-b-30">
                    <!-- begin page title -->
                    <div class="d-block d-lg-flex flex-nowrap align-items-center">
                        <div class="page-title mr-4 pr-4 border-right">
                            <h1>Dashboard</h1>
                        </div>


                    </div>
                    <!-- end page title -->
                </div>
            </div>
            <!-- Notification -->
            <!-- begin row -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="card card-statistics">
                        <div class="row no-gutters">
                            <div class="col-xxl-3 col-lg-6">
                                <div class="p-20 border-lg-right border-bottom border-xxl-bottom-0">
                                    <div class="d-flex m-b-10">
                                        <p class="mb-0 font-regular text-muted font-weight-bold">Total Accident</p>
                                        <a class="mb-0 ml-auto font-weight-bold" href="#"><i class="ti ti-more-alt"></i> </a>
                                    </div>
                                    <div class="d-block d-sm-flex h-100 align-items-center">
                                        <div class="apexchart-wrapper">
                                            <div id="analytics7"></div>
                                        </div>
                                        <div class="statistics mt-3 mt-sm-0 ml-sm-auto text-center text-sm-right">
                                            <h3 class="mb-0"><i class="icon-arrow-up-circle"></i> @ViewBag.totalaccident</h3>
                                            <p>This Year</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xxl-3 col-lg-6">
                                <div class="p-20 border-xxl-right border-bottom border-xxl-bottom-0">
                                    <div class="d-flex m-b-10">
                                        <p class="mb-0 font-regular text-muted font-weight-bold">Lost Vehicle Report</p>
                                        <a class="mb-0 ml-auto font-weight-bold" href="#"><i class="ti ti-more-alt"></i> </a>
                                    </div>
                                    <div class="d-block d-sm-flex h-100 align-items-center">
                                        <div class="apexchart-wrapper">
                                            <div id="analytics8"></div>
                                        </div>
                                        <div class="statistics mt-3 mt-sm-0 ml-sm-auto text-center text-sm-right">
                                            <h3 class="mb-0"><i class="icon-arrow-up-circle"></i> @ViewBag.totallostvehicle</h3>
                                            <p>This Year</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xxl-3 col-lg-6">
                                <div class="p-20 border-lg-right border-bottom border-lg-bottom-0">
                                    <div class="d-flex m-b-10">
                                        <p class="mb-0 font-regular text-muted font-weight-bold">Total Users</p>
                                        <a class="mb-0 ml-auto font-weight-bold" href="#"><i class="ti ti-more-alt"></i> </a>
                                    </div>
                                    <div class="d-block d-sm-flex h-100 align-items-center">
                                        <div class="apexchart-wrapper">
                                            <div id="analytics9"></div>
                                        </div>
                                        <div class="statistics mt-3 mt-sm-0 ml-sm-auto text-center text-sm-right">
                                            <h3 class="mb-0"><i class="icon-arrow-up-circle"></i>@ViewBag.totaluser</h3>
                                            <!--<p>Avg. Sales per day</p>-->
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xxl-3 col-lg-6">
                                <div class="p-20">
                                    <div class="d-block d-sm-flex h-100 align-items-center">
                                        <div class="apexchart-wrapper">
                                            <div id="analytics10"></div>
                                        </div>
                                        <div class="statistics ml-sm-auto mt-4 mt-sm-0 pr-sm-5">
                                            <ul class="list-style-none p-0">
                                                <li class="d-flex py-1">
                                                    <span><i class="fa fa-circle text-primary pr-2"></i> Redirect Visits</span> <span class="pl-2 font-weight-bold">456</span>
                                                </li>
                                                <li class="d-flex py-1"><span><i class="fa fa-circle text-warning pr-2"></i> New Visits</span> <span class="pl-2 font-weight-bold">256</span></li>
                                                <li class="d-flex py-1"><span><i class="fa fa-circle text-info pr-2"></i> Direct Visits</span> <span class="pl-2 font-weight-bold">128</span></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

EmergencyAccidentReporting/Views/Admin/LostReports.cshtml
@model IEnumerable<Vehicle>
@{
    Layout = "_LayoutAdmin";
}



<div class="app-container">
    <!-- begin app-nabar -->
    <!-- end app-navbar -->
    <!-- begin app-main -->
    <div class="app-main" id="main">
        <!-- begin container-fluid -->
        <div class="container-fluid">

            <div class="row">
                <div class="col-md-12 m-b-30">
                    <!-- begin page title -->
                    <div class="d-block d-lg-flex flex-nowrap align-items-center">
                        <div class="page-title mr-4 pr-4 border-right">
                            <h1>Lost Reports</h1>
                        </div>


                    </div>
                    <!-- end page title -->
                </div>
            </div>


            <div class="row">
                <div class="col-sm-12">
                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Lost Location</th>
                                <th>Vehicle</th>
                                <th>Owner</th>
                                <th>Number</th>
                                <th>Date</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {

                                <tr>
                                    <td>@item.Id</td>
                                    <td>@item.Address</td>
                                    <td>@item.Type</td>
                                    <td>@item.OwnerName</td>
                                    <td>@item.Number</td>
                                    <td>@item.date</td>
                                    <td>@item.status</td>
                                    <td>
                                        <a role="button" class="btn btn-warning" asp-controller="Admin" asp-action="UpdateVehiclePage" asp-route-id="@item.Id">Update</a>
                                        <a role="button" class="btn btn-primary" asp-controller="Admin" asp-action="FoundVehicle" asp-route-id="@item.Id">Found</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>

EmergencyAccidentReporting/Views/Admin/ViewAccidentPage.cshtml
@model Accident
@{
    Layout = "_LayoutAdmin";

}

<div class="app-container">
    <!-- begin app-nabar -->
    <!-- end app-navbar -->
    <!-- begin app-main -->
    <div class="app-main" id="main">
        <!-- begin container-fluid -->



        <div class="container-fluid">

            <div class="row">

                <div class="col-xl-6">
                    <div class="card card-statistics">
                        <div class="card-header">
                            <div class="card-heading">
                                <h4 class="card-title">Update Accident Details</h4>
                            </div>
                        </div>
                        <div class="card-body">
                            <form method="post" class="form-horizontal" asp-action="UpdateAccidentAction" asp-controller="Admin">

                                <input hidden type="text" asp-for="Id" value="@Model.Id" />
                                <input hidden type="text" asp-for="Id" value="@Model.Geolocation" />
                                <input hidden type="text" asp-for="Date" value = "@Model.Date"/>
                                @*<input hidden type="text" asp-for="date" value="@Model." />*@



                                <div class="form-group">
                                    <label class="control-label" asp-for="Location"></label>
                                    <div class="mb-2">
                                        <input type="text" class="form-control" id="firstname1" asp-for="Location" value="@Model.Location" placeholder="Location" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label" asp-for="Contact"></label>
                                    <div class="mb-2">
                                        <input type="text" class="form-control" id="lastname1" asp-for="Contact" value="@Model.Contact" placeholder="contact no" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label" asp-for="ReportersName"></label>
                                    <div class="mb-2">
                                        <input type="text" class="form-control" id="username1" asp-for="ReportersName" value="@Model.ReportersName" placeholder="Reporters Name" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label" asp-for="Image_Urls">Image</label>

                                    <div class="mb-2">

                                        <img src="@Model.Image_Urls" style="width: 150px;height: 150px;" />
                                    </div>

                                </div>



                                <div class="form-group">
                                    @*<button type="submit" class="btn btn-primary">
                                        Update
                                        </button>*@

                                    <button type="submit">  Update</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

EmergencyAccidentReporting/Views/Admin/ViewEvents.cshtml
@model IEnumerable<Events>
@{
    Layout = "_LayoutAdmin";
}

<div class="app-container">
    <!-- begin app-nabar -->
    <!-- end app-navbar -->
    <!-- begin app-main -->
    <div class="app-main" id="main">
        <!-- begin container-fluid -->
        <div class="container-fluid">

            <div class="row">
                <div class="col-md-12 m-b-30">
                    <!-- begin page title -->
                    <div class="d-block d-lg-flex flex-nowrap align-items-center">
                        <div class="page-title mr-4 pr-4 border-right">
                            <h1>Events Register</h1>
                        </div>
                    </div>
                    <!-- end page title -->
                </div>
            </div>

            <section id="services" class="services">
                <div class="container" data-aos="fade-up">
                    <div class="row gy-5">

                        @foreach (var item in Model)
                        {
                            <div class="col-xl-4 col-md-6" data-aos="zoom-in" data-aos-delay="200">
                                <div class="service-item">
                                    <div class="img">
                                        <img src="@item.ImgUrl" class="img-fluid" style="width:300px; height:150px" alt="">
                                    </div>
                                    <a asp-controller="Events" asp-action="Index" asp-route-id="@item.Id" class="stretched-link">
                                        <div class="details position-relative">

                                            <h3>@item.Title</h3>
                                            <p>@item.EventsDetail.Substring(0,40) ...continue reading <i class="fas fa-book-reader"></i></p>
                                    </a>
                                    <a asp-action="UpdateEvent" asp-controller="Admin" asp-route-id="@item.Id">
                                        <div class="icon">
                                            <i class="fas fa-edit"></i>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        }
                    </div>
                </div>

            </section>
        </div>