EmergencyAccidentReporting/Models/Accident.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EmergencyAccidentReporting.Models
{
    [Table("accident")]
    public class Accident
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Number { get; set; }//vehicle number
        public string Location { get; set; }
        public string Contact { get; set; }
        public string Image_Urls { get; set; }
        public string ReportersName { get; set; }
        public string Geolocation { get; set; }
        public string Date { get; set; }
    }

    public class AccidentViewModel
    {

        [Required]
        [DisplayName("Vehicle Number")]
        public string Number { get; set; }//vehicle number
        [Required]

        //code to give the location cordinates.
        public string Location { get; set; }


        [Required]
        [MaxLength(10, ErrorMessage = "phone number should have 10 numbers")]
        [MinLength(10, ErrorMessage = "phone number should have 10 numbers")]
        public string Contact { get; set; }

        [Required(ErrorMessage = "please insert the image of accidental area")]
        [DisplayName("Photo")]
        public IFormFile file { get; set; }

        [Required]
        [DisplayName("Reporters Name")]
        public string ReportersName { get; set; }

        public string Geolocation { get; set; }

        public string? mycoordinate { get; set; }
        public string Date { get; set; }
    }
}

EmergencyAccidentReporting/Controllers/ReportController.cs
using EmergencyAccidentReporting.Models;
using Microsoft.AspNetCore.Mvc;

namespace EmergencyAccidentReporting.Controllers
{
    public class ReportController : Controller
    {

        private readonly IWebHostEnvironment _webHostEnvironment;
        public ReportController(IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
        }

        DataContext dal = new DataContext();



        #region Vehicle

        //get
        public IActionResult LostVehicle()
        {
            ViewData["Title"] = "Lost Vehicle";

            ViewBag.type = new List<string>() { "Motorcycle", "Scooter", "Moped", "Car", "jeep", "Delivery Van", "Tempo", "Auto Rickshaw", "Tractor", "Lorrey", "Bus" };

            return View();

        }
        //post

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LostVehicle(Vehicle vehicle)
        {
            ViewData["Title"] = "Lost Vehicle";


            vehicle.status = "pending";
            vehicle.date = DateTime.Now.ToString("MM/dd/yyyy");
            ModelState.Remove("status");//removing status from validation check. 
            ModelState.Remove("date");

            if (ModelState.IsValid)
            {
                dal.Add(vehicle);
                dal.SaveChanges();
                return RedirectToAction("Index", "Landing");//dialogue box to ensure the given data is correct.
            }
            ViewBag.type = new List<string>() { "Motorcycle", "Scooter", "Moped", "Car", "jeep", "Delivery Van", "Tempo", "Auto Rickshaw", "Tractor", "Lorrey", "Bus" };

            return View(vehicle);
        }
        #endregion

        #region Non View Functions
        /// <summary>
        /// 1. UploadImage
        /// </summary>
        /// <returns></returns>
        public async Task<string> UploadImage(string folderpath, IFormFile file)
        {
            folderpath += Guid.NewGuid().ToString() + "_" + file.FileName;
            string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folderpath);
            await file.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
            return "/" + folderpath;
        }
        #endregion

        //multiple image insertion.




        #region Accident

        //get
        public IActionResult Accident()
        {
            ViewData["Title"] = "Accident";

            return View();
        }

        //post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Accident(AccidentViewModel AccidentReport)
        {
            ViewData["Title"] = "Accident";

            string folderpath = "image/";

            ModelState.Remove("Date");
            ModelState.Remove("mycoordinate");

            if (ModelState.IsValid)
            {

                Accident accident = new Accident()
                {
                    Number = AccidentReport.Number,
                    Image_Urls = await UploadImage(folderpath, AccidentReport.file),
                    Contact = AccidentReport.Contact,
                    Location = AccidentReport.Location,
                    ReportersName = AccidentReport.ReportersName,
                    Geolocation = AccidentReport.Geolocation,
                    Date = DateTime.Now.ToString("MM/dd/yyyy"),
                };
                //product.ImageUrl = "hello";//await UploadImage(folderpath, file); //use the function here from Doctor Patient Model

                dal.accidents.Add(accident);
                dal.SaveChanges();
                return RedirectToAction("Index", "Landing");
            }
            return View(AccidentReport);
        }
        #endregion





        ///test
        ///


    }
}

EmergencyAccidentReporting/Views/Report/Accident.cshtml
@model AccidentViewModel
@{
    Layout = "_LayoutLanding";
}

<br />
<br />
<br />
<br />


<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Au Register Forms by Colorlib</title>

    <!-- Icons font CSS-->
    <link href="~/vehicle/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">
    <link href="~/vehicle/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">

    <!-- Vendor CSS-->

    <link href="~/vehicle/vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="~/vehicle/vendor/datepicker/daterangepicker.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="~/vehicle/css/main.css" rel="stylesheet" media="all">
</head>



@section Scripts{

    <script>
        const x = document.getElementById("demo");
        function getLocation() {
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(showPosition);
            } else {
                x.innerHTML = "Geolocation is not supported by this browser.";
            }
        }

        function showPosition(position) {


            console.log(position.coords.latitude);
            console.log(position.coords.longitude);
            var lat = position.coords.latitude;
            var lon = position.coords.longitude;
            var concatedvalue = lat +","+ lon;

            document.getElementById("coordinate").value = lat+","+lon;
            

        }

        getLocation();

    </script>
}

    <div style="background:#0ea2bd;" class="page-wrapper p-t-45 p-b-50">
        <p id="x"></p>
        <div class="wrapper wrapper--w790">
            <div class="card card-5">
                <div class="card-heading">
                    <h2 class="title">Accident Report Form</h2>
                </div>
                <div class="card-body">
                    <form id="signupForm1" method="post" enctype="multipart/form-data" asp-controller="Report" asp-action="Accident" class="form-horizontal">
                        <div class="form-group">
                            <div asp-validation-summary="All">
                            </div>
                        </div>


                         <div class="form-row">
                            
                            <div class="value">
                                <div class="input-group">
                                    <input id="coordinate" class="input--style-5" type="text" asp-for="Geolocation" hidden>
                                </div>

                            </div>
                        </div>

                        <div class="form-row">
                            <div class="name">
                                <label class="control-label" asp-for="Number"></label>

                            </div>
                            <div class="value">
                                <div class="input-group">
                                    <input class="input--style-5" type="text" asp-for="Number">
                                </div>
                                <span class="text-danger" asp-validation-for="Number"></span>

                            </div>
                        </div>
                        <div class="form-row">
                            <div class="name">
                                <label class="control-label" asp-for="Location"></label>

                            </div>
                            <div class="value">
                                <div class="input-group">
                                    <input class="input--style-5" type="text" asp-for="Location">
                                </div>
                                <span class="text-danger" asp-validation-for="Location"></span>

                            </div>
                        </div>
                        <div class="form-row">
                            <div class="name">
                                <label class="control-label" asp-for="Contact"></label>

                            </div>
                            <div class="value">
                                <div class="input-group">
                                    <input class="input--style-5" type="text" asp-for="Contact">
                                </div>
                                <span class="text-danger" asp-validation-for="Contact"></span>

                            </div>
                        </div>
                        <div class="form-row">
                            <div class="name">
                                <label class="control-label" asp-for="file"></label>

                            </div>
                            <div class="value">
                                <div class="input-group">
                                    <input type="file" class="form-control" id="email1" asp-for="file" placeholder="Photos" accept="image/*" />
                                </div>
                                <span class="text-danger" asp-validation-for="file"></span>

                            </div>
                        </div>
                        <div class="form-row">
                            <div class="name">
                                <label class="control-label" asp-for="ReportersName"></label>

                            </div>
                            <div class="value">
                                <div class="input-group">
                                    <input class="input--style-5" type="text" asp-for="ReportersName">
                                </div>
                                <span class="text-danger" asp-validation-for="ReportersName"></span>

                            </div>
                        </div>
                        <div class="form-row">



                            <button class="btn btn--radius-2 btn--red" type="submit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


    <!-- Jquery JS-->
    <script src="~/vehicle/vendor/jquery/jquery.min.js"><script/>
    <!-- Vendor JS-->
    <script src="~/vehicle/vendor/select2/select2.min.js"></script>
    <script src="~/vehicle/vendor/datepicker/moment.min.js"></script>
    <script src="~/vehicle/vendor/datepicker/daterangepicker.js"></script>

    <!-- Main JS-->
    <script src="~/vehicle/js/global.js"></script>

EmergencyAccidentReporting/Views/Report/LostVehicle.cshtml
@model Vehicle
@{

    Layout = "_LayoutLanding";
}

<br />
<br />
<br />
<br />

<!DOCTYPE html>


<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Au Register Forms by Colorlib</title>

    <!-- Icons font CSS-->
    <link href="~/vehicle/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">
    <link href="~/vehicle/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="~/vehicle/vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="~/vehicle/vendor/datepicker/daterangepicker.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="~/vehicle/css/main.css" rel="stylesheet" media="all">
</head>


<div style="background:#0ea2bd" class="page-wrapper p-t-45 p-b-50">
    <div class="wrapper wrapper--w790">
        <div class="card card-5">
            <div class="card-heading">
                <h2 class="title">Lost Vehicle Registration Form</h2>
            </div>
            <div class="card-body">
                <form id="signupForm1" method="post" class="form-horizontal" asp-action="LostVehicle" asp-controller="Report">
                    <div class="form-group">
                        <div asp-validation-summary="All">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="name">
                            <label class="control-label" asp-for="OwnerName"></label>
                        </div>
                        <div class="value">
                            <div class="input-group">
                                <input class="input--style-5" type="text" asp-for="OwnerName">
                            </div>
                            <span class="text-danger" asp-validation-for="OwnerName"></span>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="name">
                            <label class="control-label" asp-for="Number"></label>

                        </div>
                        <div class="value">
                            <div class="input-group">
                                <input class="input--style-5" type="text" asp-for="Number" name="number">
                            </div>
                            <span class="text-danger" asp-validation-for="Number"></span>

                        </div>
                    </div>
                    <div class="form-row">
                        <div class="name">
                            <label class="control-label" asp-for="Contact"></label>

                        </div>
                        <div class="value">
                            <div class="input-group">
                                <input class="input--style-5" type="text" asp-for="Contact">
                            </div>
                            <span class="text-danger" asp-validation-for="Number"></span>

                        </div>
                    </div>
                    <div class="form-row">
                        <div class="name">
                            <label class="control-label" asp-for="Address"></label>

                        </div>
                        <div class="value">
                            <div class="input-group">
                                <input class="input--style-5" type="text" asp-for="Address">
                            </div>
                            <span class="text-danger" asp-validation-for="Number"></span>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="name">
                            <label class="control-label" asp-for="Email"></label>
                        </div>
                        <div class="value">
                            <div class="input-group">
                                <input class="input--style-5" type="email" asp-for="Email">
                            </div>
                            <span class="text-danger" asp-validation-for="Email"></span>

                        </div>
                    </div>
                    <div class="form-row">
                        <div class="name">Vehicle Type</div>
                        <div class="value">
                            <div class="input-group">
                                <div class="rs-select2 js-select-simple select--no-search">
                                     <select asp-for="Type" asp-items="new SelectList(ViewBag.type)">
                                        </select>
                                    <div class="select-dropdown"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="name">
                            <label class="control-label" asp-for="Model"></label>
                        </div>
                        <div class="value">
                            <div class="input-group">
                                <input class="input--style-5" type="text" asp-for="Model">
                            </div>
                            <span class="text-danger" asp-validation-for="Model"></span>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="name">
                            <label class="control-label" asp-for="Color"></label>

                        </div>
                        <div class="value">
                            <div class="input-group">
                                <input class="input--style-5" type="text" asp-for="Color">
                            </div>
                            <span class="text-danger" asp-validation-for="Color"></span>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="name">
                            <label class="control-label" asp-for="Description"></label>

                        </div>
                        <div class="value">
                            <div class="input-group">
                                 <textarea rows="2" class="form-control input--style-5" asp-for="Description"></textarea>
                            </div>
                            <span class="text-danger" asp-validation-for="Description"></span>
                        </div><br /><br />
                        <br />
                        <br />
                        <br />


                        <button class="btn btn--radius-2 btn--red" type="submit">Register</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<!-- Jquery JS-->
<script src="~/vehicle/vendor/jquery/jquery.min.js"></script>
<!-- Vendor JS-->
<script src="~/vehicle/vendor/select2/select2.min.js"></script>
<script src="~/vehicle/vendor/datepicker/moment.min.js"></script>
<script src="~/vehicle/vendor/datepicker/daterangepicker.js"></script>

<!-- Main JS-->
<script src="~/vehicle/js/global.js"></script>




<!-- end document-->